<?php

/**
 * @file
 * webform_paypal_smart.module
 */ 

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform_paypal_smart\WebformPaypalApi;

/**
 * Implements hook_form_alter()
 */
// function webform_paypal_smart_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  
//   switch ($form_id) {
//     case '':

//       break;
//   }
// }

/**
 * Implements hook_theme().
 */
function webform_paypal_smart_theme() {
  $info = [
    'webform_handler_webform_paypal_smart_buttons_handler_summary' => [
      'variables' => ['settings' => NULL, 'handler' => NULL],
    ],
  ];

  return $info;
}

/**
 * Create a dynamic library, based on whether Paypal is in Sandbox or Live mode
 */
function webform_paypal_smart_library_info_build() {
  // Get Webform Paypal Configuation
  $paypalConfig = \Drupal::config(WebformPaypalApi::PAYMENT_CONFIG);
  $libraries = [];

  // Default
  $libraries['paypal-sdk'] = [];

  $paypalStatus = $paypalConfig->get(WebformPaypalApi::STATUS_SETTING_NAME);
  
  $sandboxClientId = $paypalConfig->get('paypal_sandbox_client_id');
  $liveClientId = $paypalConfig->get('paypal_live_client_id');
  
  $additionalQuery = ''; // Must begin with an &

  // Switch the Client ID depending on Sandbox vs Production
  switch ($paypalStatus) {
    case WebformPaypalApi::PAYPAL_SANDBOX:
      $userClientId = $sandboxClientId;
//      $additionalQuery = '&debug=true';
    break;

    case WebformPaypalApi::PAYPAL_PRODUCTION:
      $userClientId = $liveClientId;
    break;

    default:
      \Drupal::logger(WebformPaypalApi::LOGGER_NAME)->warning('Paypal Status not set in Webform Paypal (Smart Buttons) settings. Paypal Library could not be generated');
    break;
  }

  if (empty($userClientId)) {
    \Drupal::messenger()->addMessage(
      t('Please enter your Paypal API keys at <a href="@url">the Webform Paypal Payment Settings form</a>.',
      ['@url' => \Drupal\Core\Url::fromRoute('webform_paypal_smart.admin_payment_settings_form')->toString()])
    );
    \Drupal::logger(WebformPaypalApi::LOGGER_NAME)->warning('Paypal Live Client ID not set. Paypal Library could not be generated');
    $libraries['paypal-sdk'] += [
      'version' => 1,
      'js' => [],
    ];
  }
  else {
    // Paypal Default query parameters
    // @see https://developer.paypal.com/docs/checkout/reference/customize-sdk/#query-parameters
    $paypalInitialUrl = 'https://www.paypal.com/sdk/js?currency=CAD&disable-card=amex,jcb&locale=en_CA&client-id=';

    // Unless you have really good reason to, you should always use this library to
    // include the Paypal SDK
    $libraries['paypal-sdk'] += [
      'version' => 1,
      'js' => [
        $paypalInitialUrl . $userClientId . $additionalQuery => [
          'type'=> 'external',
          'minified' => true,
        ]
      ],
    ];

    $libraries['paypal-sdk--sandbox'] = [
      'version' => 1,
      'js' => [
        $paypalInitialUrl . $sandboxClientId . $additionalQuery => [
          'type'=> 'external',
          'minified' => true,
        ]
      ],
    ];

    $libraries['paypal-sdk--live'] = [
      'version' => 1,
      'js' => [
        $paypalInitialUrl . $liveClientId . $additionalQuery => [
          'type'=> 'external',
          'minified' => true,
        ]
      ],
    ];
  }

  return $libraries;
}

/**
 * Implements hook_install
 */
function webform_paypal_smart_install() {
  // Remind developers to update their Paypal API keys
  \Drupal::messenger()->addMessage(
    t('Please enter your Paypal API keys at <a href="@url">the Webform Paypal Payment Settings form</a>.',
    ['@url' => \Drupal\Core\Url::fromRoute('webform_paypal_smart.admin_payment_settings_form')->toString()])
  );
}













